apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-cluster
  labels:
    {{- include "pre-install.labels" . | nindent 4 }}
spec:
  acme:
    email: jebin.johnson@intelops.dev
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod-cluster
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
