{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cerbos.fullname" . }}-job
  labels:
    {{- include "cerbos.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "cerbos.fullname" . }}
      labels:
        {{- include "cerbos.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-install-job
        image: "vitess/vtctlclient:v15.0.0"
        volumeMounts:
          - name: {{ include "cerbos.fullname" . }}-config
            mountPath: /config
        command: ["/bin/sh"]
        args:
        - -c
        - vtctlclient --server {{ .Values.vitess.server }} ApplySchema -- --sql="$(cat /config/cerbos-schema.sql)" cerbos
      volumes:
      - name: {{ include "cerbos.fullname" . }}-config
        configMap:
          name: {{ include "cerbos.fullname" . }}-db
{{- end }}
